version: "3.9"

services:
  moodle:
    build:
      context: "./apps/moodle"
    ports:
      - "8080:80"
    volumes:
      - ./data/moodledata:/var/www/html/moodledata
      - ./moodle:/var/www/html
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - caribia_network

  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres/data:/var/lib/postgresql
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - caribia_network

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - caribia_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

networks:
  caribia_network:
    driver: bridge
