version: "3.9"

services:
  moodle:
    image: brayhandeaza/caribia-moodle
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./data/moodledata:/var/www/html/moodledata
      - ./v4:/var/www/html   
    env_file:
      - .env    
    networks: 
      - caribia_network

  postgres:
    image: postgres:alpine   
    volumes:
      - ./data/postgres/data:/var/lib/postgresql
    env_file:
      - .env
    restart: always
    networks:
      - caribia_network

  pgbouncer:
    build:
      context: "./pgbouncer"
    container_name: pgbouncer
    restart: always
    env_file:
      - .env
    ports:
      - 6432:6432
    volumes:
      - ./pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini:ro
      - ./pgbouncer/users.txt:/etc/pgbouncer/users.txt:ro
    networks:
      - caribia_network

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - caribia_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

networks:
  caribia_network:
    driver: bridge
